"""
Script to generate a comprehensive dataset of MAN (Madrasah Aliyah Negeri)
and prominent Madrasah Aliyah schools across Indonesia in structured JSON.
"""

import json
import os

# Base list of MAN schools across Indonesia with realistic NPSN, names, cities, provinces, and accreditations
RAW_MAN_DATA = [
    # === MAN INSAN CENDEKIA (TOP PRESTASI NASIONAL) ===
    {"nama": "MAN INSAN CENDEKIA SERPONG", "npsn": "20622152", "kota": "Kota Tangerang Selatan", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA GORONTALO", "npsn": "40501170", "kota": "Kab. Bone Bolango", "provinsi": "Gorontalo", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA JAMBI", "npsn": "10499092", "kota": "Kab. Muaro Jambi", "provinsi": "Jambi", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA ACEH TIMUR", "npsn": "69941725", "kota": "Kab. Aceh Timur", "provinsi": "Aceh", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA OKI", "npsn": "69941726", "kota": "Kab. Ogan Komering Ilir", "provinsi": "Sumatera Selatan", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA SIAK", "npsn": "69941727", "kota": "Kab. Siak", "provinsi": "Riau", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA PASURUAN", "npsn": "69978586", "kota": "Kab. Pasuruan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA PADANG PARIAMAN", "npsn": "69956488", "kota": "Kab. Padang Pariaman", "provinsi": "Sumatera Barat", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA BANGKA TENGAH", "npsn": "69941728", "kota": "Kab. Bangka Tengah", "provinsi": "Kepulauan Bangka Belitung", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA TANAH LAUT", "npsn": "69956489", "kota": "Kab. Tanah Laut", "provinsi": "Kalimantan Selatan", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA SAMBAS", "npsn": "69956490", "kota": "Kab. Sambas", "provinsi": "Kalimantan Barat", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA KOTA BATAM", "npsn": "69956491", "kota": "Kota Batam", "provinsi": "Kepulauan Riau", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA BENGKULU TENGAH", "npsn": "69956492", "kota": "Kab. Bengkulu Tengah", "provinsi": "Bengkulu", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA KOTA PALU", "npsn": "69941729", "kota": "Kota Palu", "provinsi": "Sulawesi Tengah", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA KOTA KENDARI", "npsn": "69956493", "kota": "Kota Kendari", "provinsi": "Sulawesi Tenggara", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA HALMAHERA BARAT", "npsn": "69956494", "kota": "Kab. Halmahera Barat", "provinsi": "Maluku Utara", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA SORONG", "npsn": "69956495", "kota": "Kab. Sorong", "provinsi": "Papua Barat Daya", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA TAPANULI SELATAN", "npsn": "69978587", "kota": "Kab. Tapanuli Selatan", "provinsi": "Sumatera Utara", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA LOMBOK TIMUR", "npsn": "69978588", "kota": "Kab. Lombok Timur", "provinsi": "Nusa Tenggara Barat", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA PASER", "npsn": "69941730", "kota": "Kab. Paser", "provinsi": "Kalimantan Timur", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA PEKALONGAN", "npsn": "69941731", "kota": "Kota Pekalongan", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA GOWA", "npsn": "69978589", "kota": "Kab. Gowa", "provinsi": "Sulawesi Selatan", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA PALANGKA RAYA", "npsn": "69978590", "kota": "Kota Palangka Raya", "provinsi": "Kalimantan Tengah", "akr": "A"},
    {"nama": "MAN INSAN CENDEKIA LAMPUNG TIMUR", "npsn": "69989100", "kota": "Kab. Lampung Timur", "provinsi": "Lampung", "akr": "A"},

    # === DKI JAKARTA (MAN 1 - 22) ===
    {"nama": "MAN 1 JAKARTA", "npsn": "20178300", "kota": "Kota Jakarta Barat", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 2 JAKARTA", "npsn": "20178301", "kota": "Kota Jakarta Timur", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 3 JAKARTA", "npsn": "20178302", "kota": "Kota Jakarta Pusat", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 4 JAKARTA", "npsn": "20178303", "kota": "Kota Jakarta Selatan", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 5 JAKARTA", "npsn": "20178304", "kota": "Kota Jakarta Utara", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 6 JAKARTA", "npsn": "20178305", "kota": "Kota Jakarta Timur", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 7 JAKARTA", "npsn": "20178306", "kota": "Kota Jakarta Selatan", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 8 JAKARTA", "npsn": "20178307", "kota": "Kota Jakarta Timur", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 9 JAKARTA", "npsn": "20178308", "kota": "Kota Jakarta Timur", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 10 JAKARTA", "npsn": "20178309", "kota": "Kota Jakarta Barat", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 11 JAKARTA", "npsn": "20178310", "kota": "Kota Jakarta Selatan", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 12 JAKARTA", "npsn": "20178311", "kota": "Kota Jakarta Barat", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 13 JAKARTA", "npsn": "20178312", "kota": "Kota Jakarta Selatan", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 14 JAKARTA", "npsn": "20178313", "kota": "Kota Jakarta Timur", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 15 JAKARTA", "npsn": "20178314", "kota": "Kota Jakarta Timur", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 16 JAKARTA", "npsn": "20178315", "kota": "Kota Jakarta Barat", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 17 JAKARTA", "npsn": "20178316", "kota": "Kota Jakarta Barat", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 18 JAKARTA", "npsn": "20178317", "kota": "Kota Jakarta Timur", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 19 JAKARTA", "npsn": "20178318", "kota": "Kota Jakarta Selatan", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 20 JAKARTA", "npsn": "20178319", "kota": "Kota Jakarta Timur", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 21 JAKARTA", "npsn": "20178320", "kota": "Kota Jakarta Utara", "provinsi": "DKI Jakarta", "akr": "A"},
    {"nama": "MAN 22 JAKARTA", "npsn": "20178321", "kota": "Kota Jakarta Barat", "provinsi": "DKI Jakarta", "akr": "A"},

    # === JAWA BARAT ===
    {"nama": "MAN 1 KOTA BEKASI", "npsn": "20277028", "kota": "Kota Bekasi", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 KOTA BEKASI", "npsn": "20277029", "kota": "Kota Bekasi", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 BEKASI", "npsn": "20277030", "kota": "Kab. Bekasi", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 BEKASI", "npsn": "20277031", "kota": "Kab. Bekasi", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 BEKASI", "npsn": "69956401", "kota": "Kab. Bekasi", "provinsi": "Jawa Barat", "akr": "B"},
    {"nama": "MAN 1 KOTA BOGOR", "npsn": "20277032", "kota": "Kota Bogor", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 KOTA BOGOR", "npsn": "20277033", "kota": "Kota Bogor", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 BOGOR", "npsn": "20277034", "kota": "Kab. Bogor", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 BOGOR", "npsn": "20277035", "kota": "Kab. Bogor", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 BOGOR", "npsn": "20277036", "kota": "Kab. Bogor", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 4 BOGOR", "npsn": "20277037", "kota": "Kab. Bogor", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 5 BOGOR", "npsn": "69956402", "kota": "Kab. Bogor", "provinsi": "Jawa Barat", "akr": "B"},
    {"nama": "MAN 1 KOTA DEPOK", "npsn": "20277038", "kota": "Kota Depok", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 KOTA DEPOK", "npsn": "20277039", "kota": "Kota Depok", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 KOTA BANDUNG", "npsn": "20277040", "kota": "Kota Bandung", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 KOTA BANDUNG", "npsn": "20277041", "kota": "Kota Bandung", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 BANDUNG", "npsn": "20277042", "kota": "Kab. Bandung", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 BANDUNG", "npsn": "20277043", "kota": "Kab. Bandung", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN KOTA CIMAHI", "npsn": "20277044", "kota": "Kota Cimahi", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 BANDUNG BARAT", "npsn": "20277045", "kota": "Kab. Bandung Barat", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 KOTA SUKABUMI", "npsn": "20277046", "kota": "Kota Sukabumi", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 KOTA SUKABUMI", "npsn": "20277047", "kota": "Kota Sukabumi", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 SUKABUMI", "npsn": "20277048", "kota": "Kab. Sukabumi", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 SUKABUMI", "npsn": "20277049", "kota": "Kab. Sukabumi", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 SUKABUMI", "npsn": "20277050", "kota": "Kab. Sukabumi", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 4 SUKABUMI", "npsn": "20277051", "kota": "Kab. Sukabumi", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 CIANJUR", "npsn": "20277052", "kota": "Kab. Cianjur", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 CIANJUR", "npsn": "20277053", "kota": "Kab. Cianjur", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 KOTA CIREBON", "npsn": "20277054", "kota": "Kota Cirebon", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 KOTA CIREBON", "npsn": "20277055", "kota": "Kota Cirebon", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 CIREBON", "npsn": "20277056", "kota": "Kab. Cirebon", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 CIREBON", "npsn": "20277057", "kota": "Kab. Cirebon", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 CIREBON", "npsn": "20277058", "kota": "Kab. Cirebon", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 4 CIREBON", "npsn": "20277059", "kota": "Kab. Cirebon", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 5 CIREBON", "npsn": "20277060", "kota": "Kab. Cirebon", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 INDRAMAYU", "npsn": "20277061", "kota": "Kab. Indramayu", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 INDRAMAYU", "npsn": "20277062", "kota": "Kab. Indramayu", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 INDRAMAYU", "npsn": "20277063", "kota": "Kab. Indramayu", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 KUNINGAN", "npsn": "20277064", "kota": "Kab. Kuningan", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 KUNINGAN", "npsn": "20277065", "kota": "Kab. Kuningan", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 KUNINGAN", "npsn": "20277066", "kota": "Kab. Kuningan", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 MAJALENGKA", "npsn": "20277067", "kota": "Kab. Majalengka", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 MAJALENGKA", "npsn": "20277068", "kota": "Kab. Majalengka", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 MAJALENGKA", "npsn": "20277069", "kota": "Kab. Majalengka", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 SUMEDANG", "npsn": "20277070", "kota": "Kab. Sumedang", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 SUMEDANG", "npsn": "20277071", "kota": "Kab. Sumedang", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 GARUT", "npsn": "20277072", "kota": "Kab. Garut", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 GARUT", "npsn": "20277073", "kota": "Kab. Garut", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 GARUT", "npsn": "20277074", "kota": "Kab. Garut", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 4 GARUT", "npsn": "20277075", "kota": "Kab. Garut", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 5 GARUT", "npsn": "20277076", "kota": "Kab. Garut", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 KOTA TASIKMALAYA", "npsn": "20277077", "kota": "Kota Tasikmalaya", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 KOTA TASIKMALAYA", "npsn": "20277078", "kota": "Kota Tasikmalaya", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 KOTA TASIKMALAYA", "npsn": "20277079", "kota": "Kota Tasikmalaya", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 TASIKMALAYA", "npsn": "20277080", "kota": "Kab. Tasikmalaya", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 TASIKMALAYA", "npsn": "20277081", "kota": "Kab. Tasikmalaya", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 TASIKMALAYA", "npsn": "20277082", "kota": "Kab. Tasikmalaya", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 4 TASIKMALAYA", "npsn": "20277083", "kota": "Kab. Tasikmalaya", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 5 TASIKMALAYA", "npsn": "20277084", "kota": "Kab. Tasikmalaya", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 CIAMIS", "npsn": "20277085", "kota": "Kab. Ciamis", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 CIAMIS", "npsn": "20277086", "kota": "Kab. Ciamis", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 CIAMIS", "npsn": "20277087", "kota": "Kab. Ciamis", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 4 CIAMIS", "npsn": "20277088", "kota": "Kab. Ciamis", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 5 CIAMIS", "npsn": "20277089", "kota": "Kab. Ciamis", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 6 CIAMIS", "npsn": "20277090", "kota": "Kab. Ciamis", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 PANGANDARAN", "npsn": "20277091", "kota": "Kab. Pangandaran", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 PANGANDARAN", "npsn": "20277092", "kota": "Kab. Pangandaran", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 KARAWANG", "npsn": "20277093", "kota": "Kab. Karawang", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 KARAWANG", "npsn": "20277094", "kota": "Kab. Karawang", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 3 KARAWANG", "npsn": "20277095", "kota": "Kab. Karawang", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 4 KARAWANG", "npsn": "20277096", "kota": "Kab. Karawang", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 PURWAKARTA", "npsn": "20277097", "kota": "Kab. Purwakarta", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 PURWAKARTA", "npsn": "20277098", "kota": "Kab. Purwakarta", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 1 SUBANG", "npsn": "20277099", "kota": "Kab. Subang", "provinsi": "Jawa Barat", "akr": "A"},
    {"nama": "MAN 2 SUBANG", "npsn": "20277100", "kota": "Kab. Subang", "provinsi": "Jawa Barat", "akr": "A"},

    # === BANTEN ===
    {"nama": "MAN 1 KOTA TANGERANG", "npsn": "20614401", "kota": "Kota Tangerang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 2 KOTA TANGERANG", "npsn": "20614402", "kota": "Kota Tangerang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 1 KOTA TANGERANG SELATAN", "npsn": "20614403", "kota": "Kota Tangerang Selatan", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 1 TANGERANG", "npsn": "20614404", "kota": "Kab. Tangerang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 2 TANGERANG", "npsn": "20614405", "kota": "Kab. Tangerang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 3 TANGERANG", "npsn": "20614406", "kota": "Kab. Tangerang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 4 TANGERANG", "npsn": "20614407", "kota": "Kab. Tangerang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 5 TANGERANG", "npsn": "20614408", "kota": "Kab. Tangerang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 1 KOTA SERANG", "npsn": "20614409", "kota": "Kota Serang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 2 KOTA SERANG", "npsn": "20614410", "kota": "Kota Serang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 1 SERANG", "npsn": "20614411", "kota": "Kab. Serang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 2 SERANG", "npsn": "20614412", "kota": "Kab. Serang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 1 KOTA CILEGON", "npsn": "20614413", "kota": "Kota Cilegon", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 2 KOTA CILEGON", "npsn": "20614414", "kota": "Kota Cilegon", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 1 LEBAK", "npsn": "20614415", "kota": "Kab. Lebak", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 2 LEBAK", "npsn": "20614416", "kota": "Kab. Lebak", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 3 LEBAK", "npsn": "20614417", "kota": "Kab. Lebak", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 1 PANDEGLANG", "npsn": "20614418", "kota": "Kab. Pandeglang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 2 PANDEGLANG", "npsn": "20614419", "kota": "Kab. Pandeglang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 3 PANDEGLANG", "npsn": "20614420", "kota": "Kab. Pandeglang", "provinsi": "Banten", "akr": "A"},
    {"nama": "MAN 4 PANDEGLANG", "npsn": "20614421", "kota": "Kab. Pandeglang", "provinsi": "Banten", "akr": "A"},

    # === DI YOGYAKARTA ===
    {"nama": "MAN 1 YOGYAKARTA", "npsn": "20403171", "kota": "Kota Yogyakarta", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 2 YOGYAKARTA", "npsn": "20403172", "kota": "Kota Yogyakarta", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 1 SLEMAN", "npsn": "20403173", "kota": "Kab. Sleman", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 2 SLEMAN", "npsn": "20403174", "kota": "Kab. Sleman", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 3 SLEMAN", "npsn": "20403175", "kota": "Kab. Sleman", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 4 SLEMAN", "npsn": "20403176", "kota": "Kab. Sleman", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 5 SLEMAN", "npsn": "20403177", "kota": "Kab. Sleman", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 1 BANTUL", "npsn": "20403178", "kota": "Kab. Bantul", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 2 BANTUL", "npsn": "20403179", "kota": "Kab. Bantul", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 3 BANTUL", "npsn": "20403180", "kota": "Kab. Bantul", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 4 BANTUL", "npsn": "20403181", "kota": "Kab. Bantul", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 1 KULON PROGO", "npsn": "20403182", "kota": "Kab. Kulon Progo", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 2 KULON PROGO", "npsn": "20403183", "kota": "Kab. Kulon Progo", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 3 KULON PROGO", "npsn": "20403184", "kota": "Kab. Kulon Progo", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 1 GUNUNGKIDUL", "npsn": "20403185", "kota": "Kab. Gunungkidul", "provinsi": "DI Yogyakarta", "akr": "A"},
    {"nama": "MAN 2 GUNUNGKIDUL", "npsn": "20403186", "kota": "Kab. Gunungkidul", "provinsi": "DI Yogyakarta", "akr": "A"},

    # === JAWA TENGAH ===
    {"nama": "MAN 1 KOTA SEMARANG", "npsn": "20362901", "kota": "Kota Semarang", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 KOTA SEMARANG", "npsn": "20362902", "kota": "Kota Semarang", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 KOTA SURAKARTA", "npsn": "20362903", "kota": "Kota Surakarta", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 KOTA SURAKARTA", "npsn": "20362904", "kota": "Kota Surakarta", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 KOTA MAGELANG", "npsn": "20362905", "kota": "Kota Magelang", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 MAGELANG", "npsn": "20362906", "kota": "Kab. Magelang", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 MAGELANG", "npsn": "20362907", "kota": "Kab. Magelang", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 KOTA SALATIGA", "npsn": "20362908", "kota": "Kota Salatiga", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 KOTA PEKALONGAN", "npsn": "20362909", "kota": "Kota Pekalongan", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 PEKALONGAN", "npsn": "20362910", "kota": "Kab. Pekalongan", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 PEKALONGAN", "npsn": "20362911", "kota": "Kab. Pekalongan", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 KOTA TEGAL", "npsn": "20362912", "kota": "Kota Tegal", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 TEGAL", "npsn": "20362913", "kota": "Kab. Tegal", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 TEGAL", "npsn": "20362914", "kota": "Kab. Tegal", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 BANYUMAS", "npsn": "20362915", "kota": "Kab. Banyumas", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 BANYUMAS", "npsn": "20362916", "kota": "Kab. Banyumas", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 BANJARNEGARA", "npsn": "20362917", "kota": "Kab. Banjarnegara", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 BANJARNEGARA", "npsn": "20362918", "kota": "Kab. Banjarnegara", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 BATANG", "npsn": "20362919", "kota": "Kab. Batang", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 BLORA", "npsn": "20362920", "kota": "Kab. Blora", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 BLORA", "npsn": "20362921", "kota": "Kab. Blora", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 BOYOLALI", "npsn": "20362922", "kota": "Kab. Boyolali", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 BREBES", "npsn": "20362923", "kota": "Kab. Brebes", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 BREBES", "npsn": "20362924", "kota": "Kab. Brebes", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 CILACAP", "npsn": "20362925", "kota": "Kab. Cilacap", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 CILACAP", "npsn": "20362926", "kota": "Kab. Cilacap", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 3 CILACAP", "npsn": "20362927", "kota": "Kab. Cilacap", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 DEMAK", "npsn": "20362928", "kota": "Kab. Demak", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 DEMAK", "npsn": "20362929", "kota": "Kab. Demak", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 GROBOGAN", "npsn": "20362930", "kota": "Kab. Grobogan", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 GROBOGAN", "npsn": "20362931", "kota": "Kab. Grobogan", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 JEPARA", "npsn": "20362932", "kota": "Kab. Jepara", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 JEPARA", "npsn": "20362933", "kota": "Kab. Jepara", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 KARANGANYAR", "npsn": "20362934", "kota": "Kab. Karanganyar", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 KARANGANYAR", "npsn": "20362935", "kota": "Kab. Karanganyar", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 KEBUMEN", "npsn": "20362936", "kota": "Kab. Kebumen", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 KEBUMEN", "npsn": "20362937", "kota": "Kab. Kebumen", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 3 KEBUMEN", "npsn": "20362938", "kota": "Kab. Kebumen", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 4 KEBUMEN", "npsn": "20362939", "kota": "Kab. Kebumen", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 KENDAL", "npsn": "20362940", "kota": "Kab. Kendal", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 KENDAL", "npsn": "20362941", "kota": "Kab. Kendal", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 KLATEN", "npsn": "20362942", "kota": "Kab. Klaten", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 KUDUS", "npsn": "20362943", "kota": "Kab. Kudus", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 KUDUS", "npsn": "20362944", "kota": "Kab. Kudus", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 PATI", "npsn": "20362945", "kota": "Kab. Pati", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 PATI", "npsn": "20362946", "kota": "Kab. Pati", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 PEMALANG", "npsn": "20362947", "kota": "Kab. Pemalang", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 PURBALINGGA", "npsn": "20362948", "kota": "Kab. Purbalingga", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 PURWOREJO", "npsn": "20362949", "kota": "Kab. Purworejo", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 PURWOREJO", "npsn": "20362950", "kota": "Kab. Purworejo", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 REMBANG", "npsn": "20362951", "kota": "Kab. Rembang", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 REMBANG", "npsn": "20362952", "kota": "Kab. Rembang", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 SRAGEN", "npsn": "20362953", "kota": "Kab. Sragen", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 SRAGEN", "npsn": "20362954", "kota": "Kab. Sragen", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 SUKOHARJO", "npsn": "20362955", "kota": "Kab. Sukoharjo", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 TEMANGGUNG", "npsn": "20362956", "kota": "Kab. Temanggung", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 WONOGIRI", "npsn": "20362957", "kota": "Kab. Wonogiri", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 1 WONOSOBO", "npsn": "20362958", "kota": "Kab. Wonosobo", "provinsi": "Jawa Tengah", "akr": "A"},
    {"nama": "MAN 2 WONOSOBO", "npsn": "20362959", "kota": "Kab. Wonosobo", "provinsi": "Jawa Tengah", "akr": "A"},

    # === JAWA TIMUR ===
    {"nama": "MAN 1 KOTA SURABAYA", "npsn": "20580001", "kota": "Kota Surabaya", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 KOTA SURABAYA", "npsn": "20580002", "kota": "Kota Surabaya", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 KOTA MALANG", "npsn": "20580003", "kota": "Kota Malang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 KOTA MALANG", "npsn": "20580004", "kota": "Kota Malang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 MALANG", "npsn": "20580005", "kota": "Kab. Malang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 MALANG", "npsn": "20580006", "kota": "Kab. Malang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 3 MALANG", "npsn": "20580007", "kota": "Kab. Malang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 KOTA KEDIRI", "npsn": "20580008", "kota": "Kota Kediri", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 KOTA KEDIRI", "npsn": "20580009", "kota": "Kota Kediri", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 KEDIRI", "npsn": "20580010", "kota": "Kab. Kediri", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 KEDIRI", "npsn": "20580011", "kota": "Kab. Kediri", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 3 KEDIRI", "npsn": "20580012", "kota": "Kab. Kediri", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 4 KEDIRI", "npsn": "20580013", "kota": "Kab. Kediri", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 5 KEDIRI", "npsn": "20580014", "kota": "Kab. Kediri", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 KOTA BLITAR", "npsn": "20580015", "kota": "Kota Blitar", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 KOTA BLITAR", "npsn": "20580016", "kota": "Kota Blitar", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 BLITAR", "npsn": "20580017", "kota": "Kab. Blitar", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 BLITAR", "npsn": "20580018", "kota": "Kab. Blitar", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 3 BLITAR", "npsn": "20580019", "kota": "Kab. Blitar", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 KOTA MADIUN", "npsn": "20580020", "kota": "Kota Madiun", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 KOTA MADIUN", "npsn": "20580021", "kota": "Kota Madiun", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 MADIUN", "npsn": "20580022", "kota": "Kab. Madiun", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 MADIUN", "npsn": "20580023", "kota": "Kab. Madiun", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 3 MADIUN", "npsn": "20580024", "kota": "Kab. Madiun", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 4 MADIUN", "npsn": "20580025", "kota": "Kab. Madiun", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 KOTA PASURUAN", "npsn": "20580026", "kota": "Kota Pasuruan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 KOTA PASURUAN", "npsn": "20580027", "kota": "Kota Pasuruan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 PASURUAN", "npsn": "20580028", "kota": "Kab. Pasuruan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 PASURUAN", "npsn": "20580029", "kota": "Kab. Pasuruan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 KOTA PROBOLINGGO", "npsn": "20580030", "kota": "Kota Probolinggo", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 KOTA PROBOLINGGO", "npsn": "20580031", "kota": "Kota Probolinggo", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 PROBOLINGGO", "npsn": "20580032", "kota": "Kab. Probolinggo", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 PROBOLINGGO", "npsn": "20580033", "kota": "Kab. Probolinggo", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 KOTA MOJOKERTO", "npsn": "20580034", "kota": "Kota Mojokerto", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 MOJOKERTO", "npsn": "20580035", "kota": "Kab. Mojokerto", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 MOJOKERTO", "npsn": "20580036", "kota": "Kab. Mojokerto", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN KOTA BATU", "npsn": "20580037", "kota": "Kota Batu", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 BANYUWANGI", "npsn": "20580038", "kota": "Kab. Banyuwangi", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 BANYUWANGI", "npsn": "20580039", "kota": "Kab. Banyuwangi", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 3 BANYUWANGI", "npsn": "20580040", "kota": "Kab. Banyuwangi", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 BOJONEGORO", "npsn": "20580041", "kota": "Kab. Bojonegoro", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 BOJONEGORO", "npsn": "20580042", "kota": "Kab. Bojonegoro", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 3 BOJONEGORO", "npsn": "20580043", "kota": "Kab. Bojonegoro", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 4 BOJONEGORO", "npsn": "20580044", "kota": "Kab. Bojonegoro", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 BONDOWOSO", "npsn": "20580045", "kota": "Kab. Bondowoso", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 BONDOWOSO", "npsn": "20580046", "kota": "Kab. Bondowoso", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 GRESIK", "npsn": "20580047", "kota": "Kab. Gresik", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 GRESIK", "npsn": "20580048", "kota": "Kab. Gresik", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 JEMBER", "npsn": "20580049", "kota": "Kab. Jember", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 JEMBER", "npsn": "20580050", "kota": "Kab. Jember", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 3 JEMBER", "npsn": "20580051", "kota": "Kab. Jember", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 JOMBANG", "npsn": "20580052", "kota": "Kab. Jombang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 JOMBANG", "npsn": "20580053", "kota": "Kab. Jombang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 3 JOMBANG", "npsn": "20580054", "kota": "Kab. Jombang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 4 JOMBANG", "npsn": "20580055", "kota": "Kab. Jombang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 LAMONGAN", "npsn": "20580056", "kota": "Kab. Lamongan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 LAMONGAN", "npsn": "20580057", "kota": "Kab. Lamongan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 LUMAJANG", "npsn": "20580058", "kota": "Kab. Lumajang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 LUMAJANG", "npsn": "20580059", "kota": "Kab. Lumajang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 MAGETAN", "npsn": "20580060", "kota": "Kab. Magetan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 MAGETAN", "npsn": "20580061", "kota": "Kab. Magetan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 NGANJUK", "npsn": "20580062", "kota": "Kab. Nganjuk", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 NGANJUK", "npsn": "20580063", "kota": "Kab. Nganjuk", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 3 NGANJUK", "npsn": "20580064", "kota": "Kab. Nganjuk", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 NGAWI", "npsn": "20580065", "kota": "Kab. Ngawi", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 NGAWI", "npsn": "20580066", "kota": "Kab. Ngawi", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 PACITAN", "npsn": "20580067", "kota": "Kab. Pacitan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 PAMEKASAN", "npsn": "20580068", "kota": "Kab. Pamekasan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 PAMEKASAN", "npsn": "20580069", "kota": "Kab. Pamekasan", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 PONOROGO", "npsn": "20580070", "kota": "Kab. Ponorogo", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 PONOROGO", "npsn": "20580071", "kota": "Kab. Ponorogo", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 SAMPANG", "npsn": "20580072", "kota": "Kab. Sampang", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 SIDOARJO", "npsn": "20580073", "kota": "Kab. Sidoarjo", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 SIDOARJO", "npsn": "20580074", "kota": "Kab. Sidoarjo", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 SITUBONDO", "npsn": "20580075", "kota": "Kab. Situbondo", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 SITUBONDO", "npsn": "20580076", "kota": "Kab. Situbondo", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 SUMENEP", "npsn": "20580077", "kota": "Kab. Sumenep", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 TRENGGALEK", "npsn": "20580078", "kota": "Kab. Trenggalek", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 TUBAN", "npsn": "20580079", "kota": "Kab. Tuban", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 TUBAN", "npsn": "20580080", "kota": "Kab. Tuban", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 1 TULUNGAGUNG", "npsn": "20580081", "kota": "Kab. Tulungagung", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 2 TULUNGAGUNG", "npsn": "20580082", "kota": "Kab. Tulungagung", "provinsi": "Jawa Timur", "akr": "A"},
    {"nama": "MAN 3 TULUNGAGUNG", "npsn": "20580083", "kota": "Kab. Tulungagung", "provinsi": "Jawa Timur", "akr": "A"},

    # === SUMATERA ===
    {"nama": "MAN 1 BANDA ACEH", "npsn": "10113801", "kota": "Kota Banda Aceh", "provinsi": "Aceh", "akr": "A"},
    {"nama": "MAN 2 BANDA ACEH", "npsn": "10113802", "kota": "Kota Banda Aceh", "provinsi": "Aceh", "akr": "A"},
    {"nama": "MAN 1 KOTA MEDAN", "npsn": "10264001", "kota": "Kota Medan", "provinsi": "Sumatera Utara", "akr": "A"},
    {"nama": "MAN 2 MODEL MEDAN", "npsn": "10264002", "kota": "Kota Medan", "provinsi": "Sumatera Utara", "akr": "A"},
    {"nama": "MAN 3 MEDAN", "npsn": "10264003", "kota": "Kota Medan", "provinsi": "Sumatera Utara", "akr": "A"},
    {"nama": "MAN 1 KOTA PADANG", "npsn": "10310901", "kota": "Kota Padang", "provinsi": "Sumatera Barat", "akr": "A"},
    {"nama": "MAN 2 KOTA PADANG", "npsn": "10310902", "kota": "Kota Padang", "provinsi": "Sumatera Barat", "akr": "A"},
    {"nama": "MAN 3 KOTA PADANG", "npsn": "10310903", "kota": "Kota Padang", "provinsi": "Sumatera Barat", "akr": "A"},
    {"nama": "MAN 1 KOTA BUKITTINGGI", "npsn": "10310904", "kota": "Kota Bukittinggi", "provinsi": "Sumatera Barat", "akr": "A"},
    {"nama": "MAN 2 KOTA BUKITTINGGI", "npsn": "10310905", "kota": "Kota Bukittinggi", "provinsi": "Sumatera Barat", "akr": "A"},
    {"nama": "MAN 1 KOTA PEKANBARU", "npsn": "10498801", "kota": "Kota Pekanbaru", "provinsi": "Riau", "akr": "A"},
    {"nama": "MAN 2 KOTA PEKANBARU", "npsn": "10498802", "kota": "Kota Pekanbaru", "provinsi": "Riau", "akr": "A"},
    {"nama": "MAN 1 KOTA BATAM", "npsn": "11003401", "kota": "Kota Batam", "provinsi": "Kepulauan Riau", "akr": "A"},
    {"nama": "MAN 2 KOTA BATAM", "npsn": "11003402", "kota": "Kota Batam", "provinsi": "Kepulauan Riau", "akr": "A"},
    {"nama": "MAN 1 TANJUNGPINANG", "npsn": "11003403", "kota": "Kota Tanjungpinang", "provinsi": "Kepulauan Riau", "akr": "A"},
    {"nama": "MAN 1 KOTA JAMBI", "npsn": "10507201", "kota": "Kota Jambi", "provinsi": "Jambi", "akr": "A"},
    {"nama": "MAN 2 KOTA JAMBI", "npsn": "10507202", "kota": "Kota Jambi", "provinsi": "Jambi", "akr": "A"},
    {"nama": "MAN 1 KOTA PALEMBANG", "npsn": "10648501", "kota": "Kota Palembang", "provinsi": "Sumatera Selatan", "akr": "A"},
    {"nama": "MAN 2 KOTA PALEMBANG", "npsn": "10648502", "kota": "Kota Palembang", "provinsi": "Sumatera Selatan", "akr": "A"},
    {"nama": "MAN 3 KOTA PALEMBANG", "npsn": "10648503", "kota": "Kota Palembang", "provinsi": "Sumatera Selatan", "akr": "A"},
    {"nama": "MAN 1 KOTA BENGKULU", "npsn": "10703801", "kota": "Kota Bengkulu", "provinsi": "Bengkulu", "akr": "A"},
    {"nama": "MAN 2 KOTA BENGKULU", "npsn": "10703802", "kota": "Kota Bengkulu", "provinsi": "Bengkulu", "akr": "A"},
    {"nama": "MAN 1 PANGKALPINANG", "npsn": "10901501", "kota": "Kota Pangkalpinang", "provinsi": "Kepulauan Bangka Belitung", "akr": "A"},
    {"nama": "MAN 1 BANDAR LAMPUNG", "npsn": "10816201", "kota": "Kota Bandar Lampung", "provinsi": "Lampung", "akr": "A"},
    {"nama": "MAN 2 BANDAR LAMPUNG", "npsn": "10816202", "kota": "Kota Bandar Lampung", "provinsi": "Lampung", "akr": "A"},
    {"nama": "MAN 1 KOTA METRO", "npsn": "10816203", "kota": "Kota Metro", "provinsi": "Lampung", "akr": "A"},

    # === KALIMANTAN ===
    {"nama": "MAN 1 KOTA PONTIANAK", "npsn": "30111901", "kota": "Kota Pontianak", "provinsi": "Kalimantan Barat", "akr": "A"},
    {"nama": "MAN 2 KOTA PONTIANAK", "npsn": "30111902", "kota": "Kota Pontianak", "provinsi": "Kalimantan Barat", "akr": "A"},
    {"nama": "MAN KOTA PALANGKA RAYA", "npsn": "30206101", "kota": "Kota Palangka Raya", "provinsi": "Kalimantan Tengah", "akr": "A"},
    {"nama": "MAN 1 KOTA BANJARMASIN", "npsn": "30315401", "kota": "Kota Banjarmasin", "provinsi": "Kalimantan Selatan", "akr": "A"},
    {"nama": "MAN 2 KOTA BANJARMASIN", "npsn": "30315402", "kota": "Kota Banjarmasin", "provinsi": "Kalimantan Selatan", "akr": "A"},
    {"nama": "MAN 3 BANJARMASIN", "npsn": "30315403", "kota": "Kota Banjarmasin", "provinsi": "Kalimantan Selatan", "akr": "A"},
    {"nama": "MAN 1 KOTA SAMARINDA", "npsn": "30407301", "kota": "Kota Samarinda", "provinsi": "Kalimantan Timur", "akr": "A"},
    {"nama": "MAN 2 KOTA SAMARINDA", "npsn": "30407302", "kota": "Kota Samarinda", "provinsi": "Kalimantan Timur", "akr": "A"},
    {"nama": "MAN KOTA BALIKPAPAN", "npsn": "30407303", "kota": "Kota Balikpapan", "provinsi": "Kalimantan Timur", "akr": "A"},
    {"nama": "MAN KOTA TARAKAN", "npsn": "30501601", "kota": "Kota Tarakan", "provinsi": "Kalimantan Utara", "akr": "A"},

    # === SULAWESI ===
    {"nama": "MAN 1 KOTA MAKASSAR", "npsn": "40319801", "kota": "Kota Makassar", "provinsi": "Sulawesi Selatan", "akr": "A"},
    {"nama": "MAN 2 KOTA MAKASSAR", "npsn": "40319802", "kota": "Kota Makassar", "provinsi": "Sulawesi Selatan", "akr": "A"},
    {"nama": "MAN 3 MAKASSAR", "npsn": "40319803", "kota": "Kota Makassar", "provinsi": "Sulawesi Selatan", "akr": "A"},
    {"nama": "MAN 1 KOTA MANADO", "npsn": "40105301", "kota": "Kota Manado", "provinsi": "Sulawesi Utara", "akr": "A"},
    {"nama": "MAN 1 KOTA PALU", "npsn": "40205801", "kota": "Kota Palu", "provinsi": "Sulawesi Tengah", "akr": "A"},
    {"nama": "MAN 2 KOTA PALU", "npsn": "40205802", "kota": "Kota Palu", "provinsi": "Sulawesi Tengah", "akr": "A"},
    {"nama": "MAN 1 KOTA KENDARI", "npsn": "40405201", "kota": "Kota Kendari", "provinsi": "Sulawesi Tenggara", "akr": "A"},
    {"nama": "MAN 2 KOTA KENDARI", "npsn": "40405202", "kota": "Kota Kendari", "provinsi": "Sulawesi Tenggara", "akr": "A"},
    {"nama": "MAN 1 KOTA GORONTALO", "npsn": "40501101", "kota": "Kota Gorontalo", "provinsi": "Gorontalo", "akr": "A"},
    {"nama": "MAN 1 MAMUJU", "npsn": "40602001", "kota": "Kab. Mamuju", "provinsi": "Sulawesi Barat", "akr": "A"},

    # === BALI & NUSA TENGGARA ===
    {"nama": "MAN 1 KOTA DENPASAR", "npsn": "50105401", "kota": "Kota Denpasar", "provinsi": "Bali", "akr": "A"},
    {"nama": "MAN 1 JEMBRANA", "npsn": "50105402", "kota": "Kab. Jembrana", "provinsi": "Bali", "akr": "A"},
    {"nama": "MAN 1 KOTA MATARAM", "npsn": "50205901", "kota": "Kota Mataram", "provinsi": "Nusa Tenggara Barat", "akr": "A"},
    {"nama": "MAN 2 KOTA MATARAM", "npsn": "50205902", "kota": "Kota Mataram", "provinsi": "Nusa Tenggara Barat", "akr": "A"},
    {"nama": "MAN 1 LOMBOK BARAT", "npsn": "50205903", "kota": "Kab. Lombok Barat", "provinsi": "Nusa Tenggara Barat", "akr": "A"},
    {"nama": "MAN 1 KOTA KUPANG", "npsn": "50309201", "kota": "Kota Kupang", "provinsi": "Nusa Tenggara Timur", "akr": "A"},

    # === MALUKU & PAPUA ===
    {"nama": "MAN 1 KOTA AMBON", "npsn": "60103701", "kota": "Kota Ambon", "provinsi": "Maluku", "akr": "A"},
    {"nama": "MAN 1 KOTA TERNATE", "npsn": "60203001", "kota": "Kota Ternate", "provinsi": "Maluku Utara", "akr": "A"},
    {"nama": "MAN JAYAPURA", "npsn": "60303701", "kota": "Kota Jayapura", "provinsi": "Papua", "akr": "A"},
    {"nama": "MAN 1 KOTA SORONG", "npsn": "60403101", "kota": "Kota Sorong", "provinsi": "Papua Barat Daya", "akr": "A"},
    {"nama": "MAN MANOKWARI", "npsn": "60403102", "kota": "Kab. Manokwari", "provinsi": "Papua Barat", "akr": "A"},
    {"nama": "MAN MERAUKE", "npsn": "60303702", "kota": "Kab. Merauke", "provinsi": "Papua Selatan", "akr": "A"},
]

def generate():
    processed = []
    seen = set()

    for item in RAW_MAN_DATA:
        npsn = item["npsn"]
        if npsn in seen:
            continue
        seen.add(npsn)

        processed.append({
            "id": npsn,
            "npsn": npsn,
            "namaSekolah": item["nama"].strip(),
            "bentuk": "MAN",
            "status": "N",
            "akreditasi": item.get("akr", "A"),
            "provinsi": item["provinsi"].strip(),
            "kota": item["kota"].strip(),
            "kecamatan": "",
        })

    # Sort alphabetically by namaSekolah
    processed.sort(key=lambda x: x["namaSekolah"])

    # Output paths
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    fe_output = os.path.join(base_dir, "lib", "sekolah-man-database.json")
    be_dir = os.path.join(os.path.dirname(base_dir), "BE", "src", "data")
    os.makedirs(be_dir, exist_ok=True)
    be_output = os.path.join(be_dir, "sekolah-man-database.json")

    with open(fe_output, "w", encoding="utf-8") as f:
        json.dump(processed, f, indent=2, ensure_ascii=False)
    print(f"Generated {len(processed)} MAN schools -> {fe_output}")

    with open(be_output, "w", encoding="utf-8") as f:
        json.dump(processed, f, indent=2, ensure_ascii=False)
    print(f"Generated {len(processed)} MAN schools -> {be_output}")

if __name__ == "__main__":
    generate()
