export interface Provinsi {
  value: string;
  label: string;
  kota: { value: string; label: string }[];
}

export const PROVINSI_DATA: Provinsi[] = [
  {
    value: "Prov. D.K.I. Jakarta",
    label: "D.K.I. Jakarta",
    kota: [
      { value: "Kota Jakarta Pusat", label: "Kota Jakarta Pusat" },
      { value: "Kota Jakarta Utara", label: "Kota Jakarta Utara" },
      { value: "Kota Jakarta Barat", label: "Kota Jakarta Barat" },
      { value: "Kota Jakarta Selatan", label: "Kota Jakarta Selatan" },
      { value: "Kota Jakarta Timur", label: "Kota Jakarta Timur" },
      { value: "Kab. Kepulauan Seribu", label: "Kab. Kepulauan Seribu" },
    ],
  },
  {
    value: "Prov. Jawa Barat",
    label: "Jawa Barat",
    kota: [
      { value: "Kota Bekasi", label: "Kota Bekasi" },
      { value: "Kab. Bekasi", label: "Kab. Bekasi" },
      { value: "Kota Bandung", label: "Kota Bandung" },
      { value: "Kab. Bandung", label: "Kab. Bandung" },
      { value: "Kab. Bandung Barat", label: "Kab. Bandung Barat" },
      { value: "Kota Bogor", label: "Kota Bogor" },
      { value: "Kab. Bogor", label: "Kab. Bogor" },
      { value: "Kota Depok", label: "Kota Depok" },
      { value: "Kota Cimahi", label: "Kota Cimahi" },
      { value: "Kota Tasikmalaya", label: "Kota Tasikmalaya" },
      { value: "Kab. Tasikmalaya", label: "Kab. Tasikmalaya" },
      { value: "Kota Cirebon", label: "Kota Cirebon" },
      { value: "Kab. Cirebon", label: "Kab. Cirebon" },
      { value: "Kota Sukabumi", label: "Kota Sukabumi" },
      { value: "Kab. Sukabumi", label: "Kab. Sukabumi" },
      { value: "Kota Banjar", label: "Kota Banjar" },
      { value: "Kab. Sumedang", label: "Kab. Sumedang" },
      { value: "Kab. Garut", label: "Kab. Garut" },
      { value: "Kab. Majalengka", label: "Kab. Majalengka" },
      { value: "Kab. Kuningan", label: "Kab. Kuningan" },
      { value: "Kab. Indramayu", label: "Kab. Indramayu" },
      { value: "Kab. Subang", label: "Kab. Subang" },
      { value: "Kab. Purwakarta", label: "Kab. Purwakarta" },
      { value: "Kab. Karawang", label: "Kab. Karawang" },
      { value: "Kab. Cianjur", label: "Kab. Cianjur" },
      { value: "Kab. Ciamis", label: "Kab. Ciamis" },
      { value: "Kab. Pangandaran", label: "Kab. Pangandaran" },
    ],
  },
  {
    value: "Prov. Jawa Tengah",
    label: "Jawa Tengah",
    kota: [
      { value: "Kota Semarang", label: "Kota Semarang" },
      { value: "Kab. Semarang", label: "Kab. Semarang" },
      { value: "Kota Surakarta", label: "Kota Surakarta (Solo)" },
      { value: "Kota Magelang", label: "Kota Magelang" },
      { value: "Kab. Magelang", label: "Kab. Magelang" },
      { value: "Kota Salatiga", label: "Kota Salatiga" },
      { value: "Kota Pekalongan", label: "Kota Pekalongan" },
      { value: "Kab. Pekalongan", label: "Kab. Pekalongan" },
      { value: "Kota Tegal", label: "Kota Tegal" },
      { value: "Kab. Tegal", label: "Kab. Tegal" },
      { value: "Kab. Demak", label: "Kab. Demak" },
      { value: "Kab. Kendal", label: "Kab. Kendal" },
      { value: "Kab. Grobogan", label: "Kab. Grobogan" },
      { value: "Kab. Boyolali", label: "Kab. Boyolali" },
      { value: "Kab. Sragen", label: "Kab. Sragen" },
      { value: "Kab. Karanganyar", label: "Kab. Karanganyar" },
      { value: "Kab. Sukoharjo", label: "Kab. Sukoharjo" },
      { value: "Kab. Wonogiri", label: "Kab. Wonogiri" },
      { value: "Kab. Klaten", label: "Kab. Klaten" },
      { value: "Kab. Purworejo", label: "Kab. Purworejo" },
      { value: "Kab. Kebumen", label: "Kab. Kebumen" },
      { value: "Kab. Temanggung", label: "Kab. Temanggung" },
      { value: "Kab. Wonosobo", label: "Kab. Wonosobo" },
      { value: "Kab. Banjarnegara", label: "Kab. Banjarnegara" },
      { value: "Kab. Purbalingga", label: "Kab. Purbalingga" },
      { value: "Kab. Banyumas", label: "Kab. Banyumas (Purwokerto)" },
      { value: "Kab. Cilacap", label: "Kab. Cilacap" },
      { value: "Kab. Brebes", label: "Kab. Brebes" },
      { value: "Kab. Pemalang", label: "Kab. Pemalang" },
      { value: "Kab. Batang", label: "Kab. Batang" },
      { value: "Kab. Blora", label: "Kab. Blora" },
      { value: "Kab. Rembang", label: "Kab. Rembang" },
      { value: "Kab. Pati", label: "Kab. Pati" },
      { value: "Kab. Kudus", label: "Kab. Kudus" },
      { value: "Kab. Jepara", label: "Kab. Jepara" },
    ],
  },
  {
    value: "Prov. Jawa Timur",
    label: "Jawa Timur",
    kota: [
      { value: "Kota Surabaya", label: "Kota Surabaya" },
      { value: "Kota Malang", label: "Kota Malang" },
      { value: "Kab. Malang", label: "Kab. Malang" },
      { value: "Kota Batu", label: "Kota Batu" },
      { value: "Kab. Sidoarjo", label: "Kab. Sidoarjo" },
      { value: "Kab. Gresik", label: "Kab. Gresik" },
      { value: "Kota Kediri", label: "Kota Kediri" },
      { value: "Kab. Kediri", label: "Kab. Kediri" },
      { value: "Kota Blitar", label: "Kota Blitar" },
      { value: "Kab. Blitar", label: "Kab. Blitar" },
      { value: "Kota Madiun", label: "Kota Madiun" },
      { value: "Kab. Madiun", label: "Kab. Madiun" },
      { value: "Kota Probolinggo", label: "Kota Probolinggo" },
      { value: "Kab. Probolinggo", label: "Kab. Probolinggo" },
      { value: "Kota Pasuruan", label: "Kota Pasuruan" },
      { value: "Kab. Pasuruan", label: "Kab. Pasuruan" },
      { value: "Kota Mojokerto", label: "Kota Mojokerto" },
      { value: "Kab. Mojokerto", label: "Kab. Mojokerto" },
      { value: "Kab. Jombang", label: "Kab. Jombang" },
      { value: "Kab. Bojonegoro", label: "Kab. Bojonegoro" },
      { value: "Kab. Tuban", label: "Kab. Tuban" },
      { value: "Kab. Lamongan", label: "Kab. Lamongan" },
      { value: "Kab. Magetan", label: "Kab. Magetan" },
      { value: "Kab. Ngawi", label: "Kab. Ngawi" },
      { value: "Kab. Nganjuk", label: "Kab. Nganjuk" },
      { value: "Kab. Tulungagung", label: "Kab. Tulungagung" },
      { value: "Kab. Trenggalek", label: "Kab. Trenggalek" },
      { value: "Kab. Ponorogo", label: "Kab. Ponorogo" },
      { value: "Kab. Pacitan", label: "Kab. Pacitan" },
      { value: "Kab. Lumajang", label: "Kab. Lumajang" },
      { value: "Kab. Bondowoso", label: "Kab. Bondowoso" },
      { value: "Kab. Situbondo", label: "Kab. Situbondo" },
      { value: "Kab. Jember", label: "Kab. Jember" },
      { value: "Kab. Banyuwangi", label: "Kab. Banyuwangi" },
      { value: "Kab. Bangkalan", label: "Kab. Bangkalan" },
      { value: "Kab. Sampang", label: "Kab. Sampang" },
      { value: "Kab. Pamekasan", label: "Kab. Pamekasan" },
      { value: "Kab. Sumenep", label: "Kab. Sumenep" },
    ],
  },
  {
    value: "Prov. Banten",
    label: "Banten",
    kota: [
      { value: "Kota Tangerang", label: "Kota Tangerang" },
      { value: "Kota Tangerang Selatan", label: "Kota Tangerang Selatan" },
      { value: "Kab. Tangerang", label: "Kab. Tangerang" },
      { value: "Kota Serang", label: "Kota Serang" },
      { value: "Kab. Serang", label: "Kab. Serang" },
      { value: "Kota Cilegon", label: "Kota Cilegon" },
      { value: "Kab. Lebak", label: "Kab. Lebak" },
      { value: "Kab. Pandeglang", label: "Kab. Pandeglang" },
    ],
  },
  {
    value: "Prov. D.I. Yogyakarta",
    label: "D.I. Yogyakarta",
    kota: [
      { value: "Kota Yogyakarta", label: "Kota Yogyakarta" },
      { value: "Kab. Sleman", label: "Kab. Sleman" },
      { value: "Kab. Bantul", label: "Kab. Bantul" },
      { value: "Kab. Gunungkidul", label: "Kab. Gunungkidul" },
      { value: "Kab. Kulon Progo", label: "Kab. Kulon Progo" },
    ],
  },
  {
    value: "Prov. Bali",
    label: "Bali",
    kota: [
      { value: "Kota Denpasar", label: "Kota Denpasar" },
      { value: "Kab. Badung", label: "Kab. Badung" },
      { value: "Kab. Gianyar", label: "Kab. Gianyar" },
      { value: "Kab. Tabanan", label: "Kab. Tabanan" },
      { value: "Kab. Buleleng", label: "Kab. Buleleng" },
      { value: "Kab. Karangasem", label: "Kab. Karangasem" },
      { value: "Kab. Klungkung", label: "Kab. Klungkung" },
      { value: "Kab. Bangli", label: "Kab. Bangli" },
      { value: "Kab. Jembrana", label: "Kab. Jembrana" },
    ],
  },
  {
    value: "Prov. Sumatera Utara",
    label: "Sumatera Utara",
    kota: [
      { value: "Kota Medan", label: "Kota Medan" },
      { value: "Kota Binjai", label: "Kota Binjai" },
      { value: "Kota Pematangsiantar", label: "Kota Pematangsiantar" },
      { value: "Kota Tanjungbalai", label: "Kota Tanjungbalai" },
      { value: "Kota Tebing Tinggi", label: "Kota Tebing Tinggi" },
      { value: "Kota Sibolga", label: "Kota Sibolga" },
      { value: "Kota Padang Sidempuan", label: "Kota Padang Sidempuan" },
      { value: "Kota Gunungsitoli", label: "Kota Gunungsitoli" },
      { value: "Kab. Deli Serdang", label: "Kab. Deli Serdang" },
      { value: "Kab. Langkat", label: "Kab. Langkat" },
      { value: "Kab. Karo", label: "Kab. Karo" },
      { value: "Kab. Simalungun", label: "Kab. Simalungun" },
      { value: "Kab. Asahan", label: "Kab. Asahan" },
      { value: "Kab. Labuhanbatu", label: "Kab. Labuhanbatu" },
      { value: "Kab. Tapanuli Utara", label: "Kab. Tapanuli Utara" },
      { value: "Kab. Tapanuli Selatan", label: "Kab. Tapanuli Selatan" },
      { value: "Kab. Tapanuli Tengah", label: "Kab. Tapanuli Tengah" },
      { value: "Kab. Serdang Bedagai", label: "Kab. Serdang Bedagai" },
      { value: "Kab. Batubara", label: "Kab. Batubara" },
    ],
  },
  {
    value: "Prov. Sumatera Barat",
    label: "Sumatera Barat",
    kota: [
      { value: "Kota Padang", label: "Kota Padang" },
      { value: "Kota Bukittinggi", label: "Kota Bukittinggi" },
      { value: "Kota Payakumbuh", label: "Kota Payakumbuh" },
      { value: "Kota Solok", label: "Kota Solok" },
      { value: "Kota Sawahlunto", label: "Kota Sawahlunto" },
      { value: "Kota Padang Panjang", label: "Kota Padang Panjang" },
      { value: "Kota Pariaman", label: "Kota Pariaman" },
      { value: "Kab. Agam", label: "Kab. Agam" },
      { value: "Kab. Tanah Datar", label: "Kab. Tanah Datar" },
      { value: "Kab. Padang Pariaman", label: "Kab. Padang Pariaman" },
      { value: "Kab. Pesisir Selatan", label: "Kab. Pesisir Selatan" },
      { value: "Kab. Solok", label: "Kab. Solok" },
      { value: "Kab. Lima Puluh Kota", label: "Kab. Lima Puluh Kota" },
      { value: "Kab. Pasaman", label: "Kab. Pasaman" },
    ],
  },
  {
    value: "Prov. Riau",
    label: "Riau",
    kota: [
      { value: "Kota Pekanbaru", label: "Kota Pekanbaru" },
      { value: "Kota Dumai", label: "Kota Dumai" },
      { value: "Kab. Kampar", label: "Kab. Kampar" },
      { value: "Kab. Siak", label: "Kab. Siak" },
      { value: "Kab. Bengkalis", label: "Kab. Bengkalis" },
      { value: "Kab. Rokan Hulu", label: "Kab. Rokan Hulu" },
      { value: "Kab. Rokan Hilir", label: "Kab. Rokan Hilir" },
      { value: "Kab. Pelalawan", label: "Kab. Pelalawan" },
      { value: "Kab. Indragiri Hulu", label: "Kab. Indragiri Hulu" },
      { value: "Kab. Indragiri Hilir", label: "Kab. Indragiri Hilir" },
      { value: "Kab. Kuantan Singingi", label: "Kab. Kuantan Singingi" },
      { value: "Kab. Kepulauan Meranti", label: "Kab. Kepulauan Meranti" },
    ],
  },
  {
    value: "Prov. Kepulauan Riau",
    label: "Kepulauan Riau",
    kota: [
      { value: "Kota Batam", label: "Kota Batam" },
      { value: "Kota Tanjungpinang", label: "Kota Tanjungpinang" },
      { value: "Kab. Bintan", label: "Kab. Bintan" },
      { value: "Kab. Karimun", label: "Kab. Karimun" },
      { value: "Kab. Natuna", label: "Kab. Natuna" },
      { value: "Kab. Lingga", label: "Kab. Lingga" },
      { value: "Kab. Kepulauan Anambas", label: "Kab. Kepulauan Anambas" },
    ],
  },
  {
    value: "Prov. Sumatera Selatan",
    label: "Sumatera Selatan",
    kota: [
      { value: "Kota Palembang", label: "Kota Palembang" },
      { value: "Kota Prabumulih", label: "Kota Prabumulih" },
      { value: "Kota Lubuklinggau", label: "Kota Lubuklinggau" },
      { value: "Kota Pagar Alam", label: "Kota Pagar Alam" },
      { value: "Kab. Ogan Komering Ilir", label: "Kab. Ogan Komering Ilir" },
      { value: "Kab. Ogan Komering Ulu", label: "Kab. Ogan Komering Ulu" },
      { value: "Kab. Muara Enim", label: "Kab. Muara Enim" },
      { value: "Kab. Lahat", label: "Kab. Lahat" },
      { value: "Kab. Musi Banyuasin", label: "Kab. Musi Banyuasin" },
      { value: "Kab. Musi Rawas", label: "Kab. Musi Rawas" },
      { value: "Kab. Banyuasin", label: "Kab. Banyuasin" },
    ],
  },
  {
    value: "Prov. Lampung",
    label: "Lampung",
    kota: [
      { value: "Kota Bandar Lampung", label: "Kota Bandar Lampung" },
      { value: "Kota Metro", label: "Kota Metro" },
      { value: "Kab. Lampung Selatan", label: "Kab. Lampung Selatan" },
      { value: "Kab. Lampung Tengah", label: "Kab. Lampung Tengah" },
      { value: "Kab. Lampung Utara", label: "Kab. Lampung Utara" },
      { value: "Kab. Lampung Barat", label: "Kab. Lampung Barat" },
      { value: "Kab. Lampung Timur", label: "Kab. Lampung Timur" },
      { value: "Kab. Tanggamus", label: "Kab. Tanggamus" },
      { value: "Kab. Pringsewu", label: "Kab. Pringsewu" },
      { value: "Kab. Pesawaran", label: "Kab. Pesawaran" },
    ],
  },
  {
    value: "Prov. Jambi",
    label: "Jambi",
    kota: [
      { value: "Kota Jambi", label: "Kota Jambi" },
      { value: "Kota Sungai Penuh", label: "Kota Sungai Penuh" },
      { value: "Kab. Muaro Jambi", label: "Kab. Muaro Jambi" },
      { value: "Kab. Batanghari", label: "Kab. Batanghari" },
      { value: "Kab. Bungo", label: "Kab. Bungo" },
      { value: "Kab. Tebo", label: "Kab. Tebo" },
      { value: "Kab. Merangin", label: "Kab. Merangin" },
      { value: "Kab. Sarolangun", label: "Kab. Sarolangun" },
      { value: "Kab. Kerinci", label: "Kab. Kerinci" },
    ],
  },
  {
    value: "Prov. Bengkulu",
    label: "Bengkulu",
    kota: [
      { value: "Kota Bengkulu", label: "Kota Bengkulu" },
      { value: "Kab. Bengkulu Utara", label: "Kab. Bengkulu Utara" },
      { value: "Kab. Bengkulu Selatan", label: "Kab. Bengkulu Selatan" },
      { value: "Kab. Rejang Lebong", label: "Kab. Rejang Lebong" },
      { value: "Kab. Mukomuko", label: "Kab. Mukomuko" },
      { value: "Kab. Seluma", label: "Kab. Seluma" },
      { value: "Kab. Kaur", label: "Kab. Kaur" },
      { value: "Kab. Kepahiang", label: "Kab. Kepahiang" },
      { value: "Kab. Lebong", label: "Kab. Lebong" },
    ],
  },
  {
    value: "Prov. Kepulauan Bangka Belitung",
    label: "Bangka Belitung",
    kota: [
      { value: "Kota Pangkalpinang", label: "Kota Pangkalpinang" },
      { value: "Kab. Bangka", label: "Kab. Bangka" },
      { value: "Kab. Bangka Barat", label: "Kab. Bangka Barat" },
      { value: "Kab. Bangka Tengah", label: "Kab. Bangka Tengah" },
      { value: "Kab. Bangka Selatan", label: "Kab. Bangka Selatan" },
      { value: "Kab. Belitung", label: "Kab. Belitung" },
      { value: "Kab. Belitung Timur", label: "Kab. Belitung Timur" },
    ],
  },
  {
    value: "Prov. Aceh",
    label: "Aceh",
    kota: [
      { value: "Kota Banda Aceh", label: "Kota Banda Aceh" },
      { value: "Kota Lhokseumawe", label: "Kota Lhokseumawe" },
      { value: "Kota Langsa", label: "Kota Langsa" },
      { value: "Kota Subulussalam", label: "Kota Subulussalam" },
      { value: "Kota Sabang", label: "Kota Sabang" },
      { value: "Kab. Aceh Besar", label: "Kab. Aceh Besar" },
      { value: "Kab. Aceh Utara", label: "Kab. Aceh Utara" },
      { value: "Kab. Aceh Timur", label: "Kab. Aceh Timur" },
      { value: "Kab. Aceh Selatan", label: "Kab. Aceh Selatan" },
      { value: "Kab. Aceh Barat", label: "Kab. Aceh Barat" },
      { value: "Kab. Aceh Tengah", label: "Kab. Aceh Tengah" },
      { value: "Kab. Bireuen", label: "Kab. Bireuen" },
      { value: "Kab. Pidie", label: "Kab. Pidie" },
    ],
  },
  {
    value: "Prov. Nusa Tenggara Barat",
    label: "Nusa Tenggara Barat",
    kota: [
      { value: "Kota Mataram", label: "Kota Mataram" },
      { value: "Kota Bima", label: "Kota Bima" },
      { value: "Kab. Lombok Barat", label: "Kab. Lombok Barat" },
      { value: "Kab. Lombok Tengah", label: "Kab. Lombok Tengah" },
      { value: "Kab. Lombok Timur", label: "Kab. Lombok Timur" },
      { value: "Kab. Lombok Utara", label: "Kab. Lombok Utara" },
      { value: "Kab. Sumbawa", label: "Kab. Sumbawa" },
      { value: "Kab. Sumbawa Barat", label: "Kab. Sumbawa Barat" },
      { value: "Kab. Dompu", label: "Kab. Dompu" },
      { value: "Kab. Bima", label: "Kab. Bima" },
    ],
  },
  {
    value: "Prov. Nusa Tenggara Timur",
    label: "Nusa Tenggara Timur",
    kota: [
      { value: "Kota Kupang", label: "Kota Kupang" },
      { value: "Kab. Kupang", label: "Kab. Kupang" },
      { value: "Kab. Timor Tengah Selatan", label: "Kab. Timor Tengah Selatan" },
      { value: "Kab. Timor Tengah Utara", label: "Kab. Timor Tengah Utara" },
      { value: "Kab. Belu", label: "Kab. Belu" },
      { value: "Kab. Sikka", label: "Kab. Sikka" },
      { value: "Kab. Ende", label: "Kab. Ende" },
      { value: "Kab. Ngada", label: "Kab. Ngada" },
      { value: "Kab. Manggarai", label: "Kab. Manggarai" },
      { value: "Kab. Manggarai Barat", label: "Kab. Manggarai Barat (Labuan Bajo)" },
      { value: "Kab. Sumba Barat", label: "Kab. Sumba Barat" },
      { value: "Kab. Sumba Timur", label: "Kab. Sumba Timur" },
    ],
  },
  {
    value: "Prov. Kalimantan Barat",
    label: "Kalimantan Barat",
    kota: [
      { value: "Kota Pontianak", label: "Kota Pontianak" },
      { value: "Kota Singkawang", label: "Kota Singkawang" },
      { value: "Kab. Kubu Raya", label: "Kab. Kubu Raya" },
      { value: "Kab. Mempawah", label: "Kab. Mempawah" },
      { value: "Kab. Sambas", label: "Kab. Sambas" },
      { value: "Kab. Sanggau", label: "Kab. Sanggau" },
      { value: "Kab. Ketapang", label: "Kab. Ketapang" },
      { value: "Kab. Sintang", label: "Kab. Sintang" },
      { value: "Kab. Kapuas Hulu", label: "Kab. Kapuas Hulu" },
    ],
  },
  {
    value: "Prov. Kalimantan Tengah",
    label: "Kalimantan Tengah",
    kota: [
      { value: "Kota Palangka Raya", label: "Kota Palangka Raya" },
      { value: "Kab. Kotawaringin Barat", label: "Kab. Kotawaringin Barat" },
      { value: "Kab. Kotawaringin Timur", label: "Kab. Kotawaringin Timur" },
      { value: "Kab. Kapuas", label: "Kab. Kapuas" },
      { value: "Kab. Barito Selatan", label: "Kab. Barito Selatan" },
      { value: "Kab. Barito Utara", label: "Kab. Barito Utara" },
      { value: "Kab. Katingan", label: "Kab. Katingan" },
    ],
  },
  {
    value: "Prov. Kalimantan Selatan",
    label: "Kalimantan Selatan",
    kota: [
      { value: "Kota Banjarmasin", label: "Kota Banjarmasin" },
      { value: "Kota Banjarbaru", label: "Kota Banjarbaru" },
      { value: "Kab. Banjar", label: "Kab. Banjar" },
      { value: "Kab. Tanah Laut", label: "Kab. Tanah Laut" },
      { value: "Kab. Tanah Bumbu", label: "Kab. Tanah Bumbu" },
      { value: "Kab. Kotabaru", label: "Kab. Kotabaru" },
      { value: "Kab. Barito Kuala", label: "Kab. Barito Kuala" },
      { value: "Kab. Tapin", label: "Kab. Tapin" },
      { value: "Kab. Hulu Sungai Selatan", label: "Kab. Hulu Sungai Selatan" },
      { value: "Kab. Hulu Sungai Tengah", label: "Kab. Hulu Sungai Tengah" },
      { value: "Kab. Hulu Sungai Utara", label: "Kab. Hulu Sungai Utara" },
      { value: "Kab. Tabalong", label: "Kab. Tabalong" },
    ],
  },
  {
    value: "Prov. Kalimantan Timur",
    label: "Kalimantan Timur",
    kota: [
      { value: "Kota Samarinda", label: "Kota Samarinda" },
      { value: "Kota Balikpapan", label: "Kota Balikpapan" },
      { value: "Kota Bontang", label: "Kota Bontang" },
      { value: "Kab. Kutai Kartanegara", label: "Kab. Kutai Kartanegara" },
      { value: "Kab. Kutai Timur", label: "Kab. Kutai Timur" },
      { value: "Kab. Kutai Barat", label: "Kab. Kutai Barat" },
      { value: "Kab. Berau", label: "Kab. Berau" },
      { value: "Kab. Paser", label: "Kab. Paser" },
      { value: "Kab. Penajam Paser Utara", label: "Kab. Penajam Paser Utara" },
    ],
  },
  {
    value: "Prov. Kalimantan Utara",
    label: "Kalimantan Utara",
    kota: [
      { value: "Kota Tarakan", label: "Kota Tarakan" },
      { value: "Kab. Bulungan", label: "Kab. Bulungan" },
      { value: "Kab. Nunukan", label: "Kab. Nunukan" },
      { value: "Kab. Malinau", label: "Kab. Malinau" },
      { value: "Kab. Tana Tidung", label: "Kab. Tana Tidung" },
    ],
  },
  {
    value: "Prov. Sulawesi Utara",
    label: "Sulawesi Utara",
    kota: [
      { value: "Kota Manado", label: "Kota Manado" },
      { value: "Kota Bitung", label: "Kota Bitung" },
      { value: "Kota Tomohon", label: "Kota Tomohon" },
      { value: "Kota Kotamobagu", label: "Kota Kotamobagu" },
      { value: "Kab. Minahasa", label: "Kab. Minahasa" },
      { value: "Kab. Minahasa Utara", label: "Kab. Minahasa Utara" },
      { value: "Kab. Minahasa Selatan", label: "Kab. Minahasa Selatan" },
      { value: "Kab. Bolaang Mongondow", label: "Kab. Bolaang Mongondow" },
    ],
  },
  {
    value: "Prov. Sulawesi Tengah",
    label: "Sulawesi Tengah",
    kota: [
      { value: "Kota Palu", label: "Kota Palu" },
      { value: "Kab. Sigi", label: "Kab. Sigi" },
      { value: "Kab. Donggala", label: "Kab. Donggala" },
      { value: "Kab. Parigi Moutong", label: "Kab. Parigi Moutong" },
      { value: "Kab. Poso", label: "Kab. Poso" },
      { value: "Kab. Banggai", label: "Kab. Banggai" },
      { value: "Kab. Tolitoli", label: "Kab. Tolitoli" },
      { value: "Kab. Buol", label: "Kab. Buol" },
    ],
  },
  {
    value: "Prov. Sulawesi Selatan",
    label: "Sulawesi Selatan",
    kota: [
      { value: "Kota Makassar", label: "Kota Makassar" },
      { value: "Kota Parepare", label: "Kota Parepare" },
      { value: "Kota Palopo", label: "Kota Palopo" },
      { value: "Kab. Gowa", label: "Kab. Gowa" },
      { value: "Kab. Maros", label: "Kab. Maros" },
      { value: "Kab. Pangkajene dan Kepulauan", label: "Kab. Pangkep" },
      { value: "Kab. Barru", label: "Kab. Barru" },
      { value: "Kab. Bone", label: "Kab. Bone" },
      { value: "Kab. Soppeng", label: "Kab. Soppeng" },
      { value: "Kab. Wajo", label: "Kab. Wajo" },
      { value: "Kab. Bulukumba", label: "Kab. Bulukumba" },
      { value: "Kab. Bantaeng", label: "Kab. Bantaeng" },
      { value: "Kab. Jeneponto", label: "Kab. Jeneponto" },
      { value: "Kab. Takalar", label: "Kab. Takalar" },
      { value: "Kab. Sinjai", label: "Kab. Sinjai" },
      { value: "Kab. Pinrang", label: "Kab. Pinrang" },
      { value: "Kab. Sidenreng Rappang", label: "Kab. Sidrap" },
      { value: "Kab. Enrekang", label: "Kab. Enrekang" },
      { value: "Kab. Luwu", label: "Kab. Luwu" },
      { value: "Kab. Luwu Utara", label: "Kab. Luwu Utara" },
      { value: "Kab. Luwu Timur", label: "Kab. Luwu Timur" },
      { value: "Kab. Tana Toraja", label: "Kab. Tana Toraja" },
      { value: "Kab. Toraja Utara", label: "Kab. Toraja Utara" },
    ],
  },
  {
    value: "Prov. Sulawesi Tenggara",
    label: "Sulawesi Tenggara",
    kota: [
      { value: "Kota Kendari", label: "Kota Kendari" },
      { value: "Kota Baubau", label: "Kota Baubau" },
      { value: "Kab. Konawe", label: "Kab. Konawe" },
      { value: "Kab. Konawe Selatan", label: "Kab. Konawe Selatan" },
      { value: "Kab. Kolaka", label: "Kab. Kolaka" },
      { value: "Kab. Muna", label: "Kab. Muna" },
      { value: "Kab. Buton", label: "Kab. Buton" },
    ],
  },
  {
    value: "Prov. Sulawesi Barat",
    label: "Sulawesi Barat",
    kota: [
      { value: "Kab. Mamuju", label: "Kab. Mamuju" },
      { value: "Kab. Majene", label: "Kab. Majene" },
      { value: "Kab. Polewali Mandar", label: "Kab. Polewali Mandar (Polman)" },
      { value: "Kab. Mamasa", label: "Kab. Mamasa" },
      { value: "Kab. Pasangkayu", label: "Kab. Pasangkayu" },
      { value: "Kab. Mamuju Tengah", label: "Kab. Mamuju Tengah" },
    ],
  },
  {
    value: "Prov. Gorontalo",
    label: "Gorontalo",
    kota: [
      { value: "Kota Gorontalo", label: "Kota Gorontalo" },
      { value: "Kab. Gorontalo", label: "Kab. Gorontalo" },
      { value: "Kab. Bone Bolango", label: "Kab. Bone Bolango" },
      { value: "Kab. Boalemo", label: "Kab. Boalemo" },
      { value: "Kab. Pohuwato", label: "Kab. Pohuwato" },
      { value: "Kab. Gorontalo Utara", label: "Kab. Gorontalo Utara" },
    ],
  },
  {
    value: "Prov. Maluku",
    label: "Maluku",
    kota: [
      { value: "Kota Ambon", label: "Kota Ambon" },
      { value: "Kota Tual", label: "Kota Tual" },
      { value: "Kab. Maluku Tengah", label: "Kab. Maluku Tengah" },
      { value: "Kab. Maluku Tenggara", label: "Kab. Maluku Tenggara" },
      { value: "Kab. Seram Bagian Barat", label: "Kab. Seram Bagian Barat" },
      { value: "Kab. Seram Bagian Timur", label: "Kab. Seram Bagian Timur" },
      { value: "Kab. Buru", label: "Kab. Buru" },
    ],
  },
  {
    value: "Prov. Maluku Utara",
    label: "Maluku Utara",
    kota: [
      { value: "Kota Ternate", label: "Kota Ternate" },
      { value: "Kota Tidore Kepulauan", label: "Kota Tidore Kepulauan" },
      { value: "Kab. Halmahera Utara", label: "Kab. Halmahera Utara" },
      { value: "Kab. Halmahera Selatan", label: "Kab. Halmahera Selatan" },
      { value: "Kab. Halmahera Barat", label: "Kab. Halmahera Barat" },
      { value: "Kab. Halmahera Timur", label: "Kab. Halmahera Timur" },
      { value: "Kab. Halmahera Tengah", label: "Kab. Halmahera Tengah" },
    ],
  },
  {
    value: "Prov. Papua",
    label: "Papua",
    kota: [
      { value: "Kota Jayapura", label: "Kota Jayapura" },
      { value: "Kab. Jayapura", label: "Kab. Jayapura" },
      { value: "Kab. Keerom", label: "Kab. Keerom" },
      { value: "Kab. Sarmi", label: "Kab. Sarmi" },
      { value: "Kab. Mamberamo Raya", label: "Kab. Mamberamo Raya" },
    ],
  },
  {
    value: "Prov. Papua Barat",
    label: "Papua Barat",
    kota: [
      { value: "Kota Sorong", label: "Kota Sorong" },
      { value: "Kab. Manokwari", label: "Kab. Manokwari" },
      { value: "Kab. Sorong", label: "Kab. Sorong" },
      { value: "Kab. Fakfak", label: "Kab. Fakfak" },
      { value: "Kab. Kaimana", label: "Kab. Kaimana" },
      { value: "Kab. Teluk Bintuni", label: "Kab. Teluk Bintuni" },
    ],
  },
];
